
    CREATE DATABASE 'kedust'

CREATE TABLE IF NOT EXISTS [Users] (
    [Id] INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    [Username] NVARCHAR(64) NOT NULL,
    [Email] NVARCHAR(128) NOT NULL,
    [Password] NVARCHAR(128) NOT NULL,
    [DateCreated] TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    )
)